import java.awt.Graphics;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;

/**
 *
 * @author Nate
 */
public class KnightFrame extends javax.swing.JFrame implements java.awt.event.ActionListener
{
    private KnightChar knightchar;
    private KnightFig knightfig;
    private VillagerFig villagerfig;
    private PotFig potfig;
    private FloorFig floorfig;
    private StoneFig stonefig;
    private GrassFig grassfig;
    private OrcFig orcfig;
    private OrcBFig orcbfig;
    int score = 0;
    int lives = 5;

    private javax.swing.Timer moveTimer = new javax.swing.Timer(500, this);
    /**
     * Creates new form KnightFrame
     */
    public KnightFrame() 
    {
        initComponents();
        knightchar = new KnightChar(jPanel1);
        knightfig = new KnightFig(jPanel1);
        villagerfig = new VillagerFig(jPanel1);
        potfig = new PotFig(jPanel1);
        floorfig = new FloorFig(jPanel1);
        stonefig = new StoneFig(jPanel1);
        grassfig = new GrassFig(jPanel1);
        orcfig = new OrcFig(jPanel1);
        orcbfig = new OrcBFig(jPanel1);
        // Start moveTimer here
        moveTimer.start();
        jPanel1.requestFocus();
    }
    @Override
    public void actionPerformed(ActionEvent ae)
    {
       stonefig.draw();
       grassfig.draw();
       floorfig.draw();
       
       knightchar.hide();
       knightchar.move();
       knightchar.draw();
       
       if ( score >= 10 )
       {
          // Draw new orc
          orcfig.hide();
          orcfig.move();
          orcfig.draw();
       }
       if ( score >= 25 )
       {
          // Draw new orc
          orcbfig.hide();
          orcbfig.move();
          orcbfig.draw();   
       }
      
       villagerfig.draw();
       potfig.draw();
       
       knightfig.draw();
       collision();
           
    }
    public void collision()
    {
       if (knightchar.collidedWith(knightfig))
       {
          //System.out.println("Attacked!");       
       }
       else if (knightfig.collidedWith(villagerfig))
       {
          score ++;
          System.out.println("Score is " + score);
       }   
       else if (knightfig.collidedWith(potfig))
       {
          score ++;
          System.out.println("Score is " + score);
       } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.gray);
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Score is Shown in Output Box");
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ScoreLabel(evt);
            }
        });
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
        knightfig.hide();
        if ( evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN )
           knightfig.move(0, 10);
        else if ( evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP )
           knightfig.move(0, -10);
        else if ( evt.getKeyCode() == java.awt.event.KeyEvent.VK_LEFT )
           knightfig.move(-10, 0);
        else if ( evt.getKeyCode() == java.awt.event.KeyEvent.VK_RIGHT )
           knightfig.move(10, 0);
           knightfig.draw();
           knightchar.draw();
    }//GEN-LAST:event_jPanel1KeyPressed

    private void ScoreLabel(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ScoreLabel
        // TODO add your handling code here:
        JLabel jLabel1 = new JLabel();
        jLabel1.setText("Score is " + score);
    }//GEN-LAST:event_ScoreLabel

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            @Override
            public void run() 
            {
                new KnightFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
